let data = [
  {
    id: 0,
    img: "/img/pd01.png",
    title: "Face Masks",
    price: 1000,
    discount: 3,
    cate1: "NEW PRODUCTS",
    cate2: "Everyday Essentials",
  },
  {
    id: 1,
    img: "/img/pd02.png",
    title: "Body Spray",
    price: 1800,
    discount: 5,
    cate1: "WEEKLY DISCOUNT",
    cate2: "Cleaning Essentials",
  },
  {
    id: 2,
    img: "/img/pd03.png",
    title: "Stay Free Ultra Pad",
    price: 5000,
    discount: 0,
    cate1: "NEW PRODUCTS",
    cate2: "Everyday Essentials",
  },
  {
    id: 3,
    img: "/img/pd04.png",
    title: "Hand Gloves",
    price: 3600,
    discount: 0,
    cate1: "TOP SELLINGS",
    cate2: "Immunity & Health",
  },
  {
    id: 4,
    img: "/img/pd05.png",
    title: "Vitamin C",
    price: 10000,
    discount: 10,
    cate1: "TOP SELLINGS",
    cate2: "Vitamin Supplements",
  },
  {
    id: 5,
    img: "/img/pd06.png",
    title: "Sanitizer",
    price: 15000,
    discount: 0,
    cate1: "WEEKLY DISCOUNT",
    cate2: "Everyday Essentials",
  },
  {
    id: 6,
    img: "/img/pd07.png",
    title: "Deodorant",
    price: 5000,
    discount: 3,
    cate1: "NEW PRODUCTS",
    cate2: "Everyday Essentials",
  },
  {
    id: 7,
    img: "/img/pd03.png",
    title: "Stay Free Ultra Pad",
    price: 5000,
    discount: 0,
    cate1: "NEW PRODUCTS",
    cate2: "Everyday Essentials",
  },
  {
    id: 8,
    img: "/img/pd07.png",
    title: "Deodorant",
    price: 5000,
    discount: 3,
    cate1: "WEEKLY DISCOUNT",
    cate2: "Everyday Essentials",
  },
];

export default data;
